// Obtener todas las propuestas
GET http://127.0.0.1:8080/api/propuesta HTTP/1.1

###
// Obtener propuesta por ID
GET http://127.0.0.1:8080/api/propuesta/681ae97085c61b12c725c343 HTTP/1.1

###
// Añadir una propuesta
POST http://127.0.0.1:8080/api/propuesta HTTP/1.1
Content-Type: application/json

{
    "title": "Test 3Propuesta",
    "category": ["Tes3t"],
    "descripcion": "Esto es una prueba",
    "date": "2025-05-05",
    "likes": 0,
    "dislikes": 0,
    "img": "https://via.placeholder.com/150",
    "autor" : "681c1b5fdb318628c63e6eb5"
}

###
// Actualizar una propuesta por ID
PUT http://127.0.0.1:8080/api/propuesta/681ae97085c61b12c725c343 HTTP/1.1
Content-Type: application/json

{
    "title": "Test Actualizado",
    "category": ["Test Updated"],
    "descripcion": "Esto es una prueba actualizada",
    "likes": 1,
    "dislikes": 0,
    "img": "https://via.placeholder.com/150"
}

###
// Eliminar una propuesta por ID
DELETE http://127.0.0.1:8080/api/propuesta/681c3b58bfbf6c18470603bf HTTP/1.1

//-------------------------------------------- REQUEST PARA USUARIOS ---------------------------------------------------------------------------

###

// Obtener todos los usuarios
GET http://127.0.0.1:8080/api/user HTTP/1.1

###
// Obtener usuario por ID
GET http://127.0.0.1:8080/api/user/681c1b5fdb318628c63e6eb5 HTTP/1.1

###
// Obtener usuario por email
GET http://127.0.0.1:8080/api/user/email/test@test.com HTTP/1.1

###
// Crear nuevo usuario
POST http://127.0.0.1:8080/api/user HTTP/1.1
Content-Type: application/json

{
    "user": "Admin",
    "role": "admin",
    "email": "admin@test.com",
    "password": "admin"
}

###
// Actualizar usuario por ID
PUT http://127.0.0.1:8080/api/user/681c3c4e1152f6ad34137473 HTTP/1.1
Content-Type: application/json

{
    "user": "UpdatedUser",
    "role": "admin",
    "email": "admin@test.com",
    "password": "admin"
}

###
// Eliminar usuario por ID
DELETE http://127.0.0.1:8080/api/user/682531d1c7f1b6e0a3f4653f HTTP/1.1