// Obtener todas las propuestas
GET http://127.0.0.1:8080/api/propuesta HTTP/1.1

###
// Obtener propuesta por ID
GET http://127.0.0.1:8080/api/propuesta/681ae97085c61b12c725c343 HTTP/1.1

###
// Añadir una propuesta
POST http://127.0.0.1:8080/api/propuesta HTTP/1.1
Content-Type: application/json

{
    "title": "Test Propuesta",
    "category": ["Test"],
    "descripcion": "Esto es una prueba",
    "date": "2025-05-05",
    "likes": 0,
    "dislikes": 0,
    "img": "https://via.placeholder.com/150"
}

###
// Actualizar una propuesta por ID
PUT http://127.0.0.1:8080/api/propuesta/681ae97085c61b12c725c343 HTTP/1.1
Content-Type: application/json

{
    "title": "Test Actualizado",
    "category": ["Test Updated"],
    "descripcion": "Esto es una prueba actualizada",
    "likes": 1,
    "dislikes": 0,
    "img": "https://via.placeholder.com/150"
}

###
// Eliminar una propuesta por ID
DELETE http://127.0.0.1:8080/api/propuesta/681ae97085c61b12c725c343 HTTP/1.1